extraScrapeConfigs: |
  - job_name: workers
    scrape_interval: 10s
    static_configs:
      - targets:
          - 10.1.2.3:9100
          - 10.1.2.3:9445
          - 10.1.2.4:9100
          - 10.1.2.4:9445
          - 10.1.2.5:9100
          - 10.1.2.5:9445
        labels:
          group: workers

#  - job_name: mgmt
#    scrape_interval: 10s
#    static_configs:
#      - targets:
#          - 172.28.10.183:9100	# nvidia-mgmt
#        labels:
#          group: mgmt
#
#  - job_name: snmp
#    scrape_interval: 15s
#    static_configs:
#      - targets:
#        - 172.28.10.135  # switch-1
#        - 172.28.10.136  # switch-2
#    metrics_path: /snmp
#    params:
#      module:
#        - if_mib
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: prometheus-snmp-exporter:9116  # The SNMP exporter's Service name and port.
server:
  retention: 10000d
