- name: Prometheus Node Exporter
  hosts: ["all"]
  tags: ["node-exporter"]
  roles:
    - cloudalchemy.node-exporter

- name: NVIDIA GPU Exporter
  hosts: ["workers"]
  tags: ["nvidia"]
  tasks:
    - shell: |
        docker rm --force nvidia_gpu_prometheus_exporter ; \
        docker run --gpus all -d \
        -p 9445:9445 \
        --restart always \
        --name nvidia_gpu_prometheus_exporter \
        mindprince/nvidia_gpu_prometheus_exporter:0.1
