- name: Slurm Management Nodes
  hosts: nvidia-mgmt
  roles:
    - ansible-slurm
  vars_files:
    - slurm_vars_constrained.yaml
  vars:
    slurm_roles: ["controller", "dbd"]

- name: Slurm Exec Nodes
  hosts: workers
  roles:
    - ansible-slurm
  vars_files:
    - slurm_vars_constrained.yaml
  vars:
    slurm_roles: ["exec"]
